# Generated by Django 4.0.4 on 2022-05-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='dem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='imgPath',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='dem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='imgPath',
            field=models.TextField(null=True),
        ),
    ]
